// User's session
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAIL = 'FETCH_CURRENT_USER_FAIL';

// Notifications

export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';

// Cheers Leaders

export const FETCH_CHEERS_LEADERS = 'FETCH_CHEERS_LEADERS';
export const FETCH_CHEERS_LEADERS_SUCCESS = 'FETCH_CHEERS_LEADERS_SUCCESS';
export const FETCH_CHEERS_LEADERS_FAIL = 'FETCH_CHEERS_LEADERS_FAIL';

// Value Tags

export const FETCH_VALUE_TAGS = 'FETCH_VALUE_TAGS';
export const FETCH_VALUE_TAGS_SUCCESS = 'FETCH_VALUE_TAGS_SUCCESS';
export const FETCH_VALUE_TAGS_FAIL = 'FETCH_VALUE_TAGS_FAIL';

// Timeline

export const FETCH_TIMELINE = 'FETCH_TIMELINE';
export const FETCH_TIMELINE_SUCCESS = 'FETCH_TIMELINE_SUCCESS';
export const FETCH_TIMELINE_FAIL = 'FETCH_TIMELINE_FAIL';

// Related Pulses

export const FETCH_RELATED_PULSES = 'FETCH_RELATED_PULSES';
export const FETCH_RELATED_PULSES_SUCCESS = 'FETCH_RELATED_PULSES_SUCCESS';
export const FETCH_RELATED_PULSES_FAIL = 'FETCH_RELATED_PULSES_FAIL';

// Recent Cheers

export const FETCH_RECENT_CHEERS = 'FETCH_RECENT_CHEERS';
export const FETCH_RECENT_CHEERS_SUCCESS = 'FETCH_RECENT_CHEERS_SUCCESS';
export const FETCH_RECENT_CHEERS_FAIL = 'FETCH_RECENT_CHEERS_FAIL';

// Metrics

export const FETCH_METRICS = 'FETCH_METRICS';
export const FETCH_METRICS_SUCCESS = 'FETCH_METRICS_SUCCESS';
export const FETCH_METRICS_FAIL = 'FETCH_METRICS_FAIL';

// Breakdown

export const FETCH_BREAKDOWN = 'FETCH_BREAKDOWN';
export const FETCH_BREAKDOWN_SUCCESS = 'FETCH_BREAKDOWN_SUCCESS';
export const FETCH_BREAKDOWN_FAIL = 'FETCH_BREAKDOWN_FAIL';

export const FETCH_SEGMENTS_BREAKDOWN = 'FETCH_SEGMENTS_BREAKDOWN';
export const FETCH_SEGMENTS_BREAKDOWN_SUCCESS =
  'FETCH_SEGMENTS_BREAKDOWN_SUCCESS';
export const FETCH_SEGMENTS_BREAKDOWN_FAIL = 'FETCH_SEGMENTS_BREAKDOWN_FAIL';
export const LOAD_MORE_SEGMENTS = 'LOAD_MORE_SEGMENTS';

// Segments

export const FETCH_SEGMENTS = 'FETCH_SEGMENTS';
export const FETCH_SEGMENTS_SUCCESS = 'FETCH_SEGMENTS_SUCCESS';
export const FETCH_SEGMENTS_FAIL = 'FETCH_SEGMENTS_FAIL';
export const SEARCH_SEGMENTS = 'SEARCH_SEGMENTS';

// Cheers Leaderboard

export const FETCH_LEADERBOARD = 'FETCH_LEADERBOARD';
export const FETCH_LEADERBOARD_SUCCESS = 'FETCH_LEADERBOARD_SUCCESS';
export const FETCH_LEADERBOARD_FAIL = 'FETCH_LEADERBOARD_FAIL';
export const RESET_LEADERBOARD = 'RESET_LEADERBOARD';

// Cheers Feed

export const FETCH_CHEERS_FEED = 'FETCH_CHEERS_FEED';
export const FETCH_CHEERS_FEED_SUCCESS = 'FETCH_CHEERS_FEED_SUCCESS';
export const FETCH_CHEERS_FEED_FAIL = 'FETCH_CHEERS_FEED_FAIL';
export const CHEERS_FEED_FETCH_LEADERBOARD = 'CHEERS_FEED_FETCH_LEADERBOARD';
export const CHEERS_FEED_FETCH_LEADERBOARD_SUCCESS =
  'CHEERS_FEED_FETCH_LEADERBOARD_SUCCESS';
export const CHEERS_FEED_FETCH_LEADERBOARD_FAIL =
  'CHEERS_FEED_FETCH_LEADERBOARD_FAIL';
export const ADD_TAG = 'ADD_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const RESET_CHEERS_FEED = 'RESET_CHEERS_FEED';
export const TOGGLE_HIDE_FROM_FEED = 'TOGGLE_HIDE_FROM_FEED';

// Export Cheers

export const EXPORT_CHEERS = 'EXPORT_CHEERS';
export const EXPORT_CHEERS_SUCCESS = 'EXPORT_CHEERS_SUCCESS';
export const EXPORT_CHEERS_FAIL = 'EXPORT_CHEERS_FAIL';

// Fitlering and sort
export const FILTER_DATE = 'FILTER_DATE';
export const FILTER_SEGMENTS = 'FILTER_SEGMENTS';
export const FILTER_KEYWORD = 'FILTER_KEYWORD';
export const FILTER_RECEIVERS = 'FILTER_RECEIVERS';
export const SORT_BY = 'SORT_BY';
export const LOAD_MORE = 'LOAD_MORE';
