export const getLeaderboard = state => state.leaderboard.leaders;
export const getLeaderboardCachedUrl = state => state.leaderboard.cachedUrl;
export const getLeaderboardPage = state => state.leaderboard.page;
export const getLeaderboardTotalPages = state => state.leaderboard.totalPages;
export const getLeaderboardSearch = state => state.leaderboard.search;
export const getLeaderboardDateFilter = state => state.leaderboard.dateFilter;
export const getLeaderboardSort = state => state.leaderboard.sort;
export const getSegmentsFilter = state => state.leaderboard.segmentsFilter.map(id => parseInt(id, 10)).filter((id) => id > 0);
export const getIsFetchingLeaderboard = state => state.leaderboard.isFetching;
export const getFetchLeaderboardError = state => state.leaderboard.errorMessage;
